# Generated by Django 4.0.2 on 2022-03-15 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.CharField(max_length=32)),
                ('timeframe', models.PositiveSmallIntegerField(choices=[(1, '1'), (5, '5'), (15, '15')])),
                ('hora', models.PositiveSmallIntegerField()),
                ('minuto', models.PositiveSmallIntegerField()),
                ('call', models.PositiveSmallIntegerField()),
                ('sell', models.PositiveSmallIntegerField()),
                ('porcent', models.PositiveSmallIntegerField()),
                ('direc', models.CharField(choices=[('CALL', 'COMPRA'), ('SELL', 'VENDA')], max_length=32)),
            ],
            options={
                'unique_together': {('par', 'timeframe', 'hora', 'minuto')},
            },
        ),
        migrations.CreateModel(
            name='Configuração',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32)),
                ('senha', models.CharField(max_length=32)),
                ('dias_salvos', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'configurações',
            },
        ),
        migrations.CreateModel(
            name='Paridade',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Apenas Letras maiúsculas permitidas')])),
            ],
        ),
        migrations.CreateModel(
            name='Vela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.CharField(max_length=32)),
                ('data', models.DateField()),
                ('timeframe', models.PositiveSmallIntegerField(choices=[(1, '1'), (5, '5'), (15, '15')])),
                ('hora', models.PositiveSmallIntegerField()),
                ('minuto', models.PositiveSmallIntegerField()),
                ('direc', models.CharField(choices=[('CALL', 'COMPRA'), ('SELL', 'VENDA')], max_length=32)),
            ],
            options={
                'unique_together': {('par', 'timeframe', 'data', 'hora', 'minuto')},
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
