# Generated by Django 4.0.2 on 2022-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('nome', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('Off', 'Off'), ('On', 'On')], default='Off', max_length=32, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('execucao', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
