# Generated by Django 4.0.2 on 2022-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
